select lncel.lncel_enb_id, lncel.lncel_lcr_id, 
 decode(sum((NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_01)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_02)+
(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_03)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_04)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_05)+
(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_06)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_07)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_08)+
(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_09)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_10)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_11)+
(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_12)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_13)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_14)+
(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_15)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_16)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_17)+
(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_18)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_19)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_20)+
(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_21)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_22)),0,-120,round(sum(-120*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_01)-119*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_02)-117*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_03)-
115*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_04)-113*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_05)-111*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_06)-
109*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_07)-107*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_08)-105*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_09)-
103*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_10)-101*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_11)-99*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_12)-
97*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_13)-95*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_14)-93*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_15)-
91*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_16)-89*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_17)-87*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_18)-
85*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_19)-83*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_20)-81*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_21)-
80*(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_22))/sum((NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_01)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_02)+
(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_03)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_04)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_05)+
(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_06)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_07)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_08)+
(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_09)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_10)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_11)+
(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_12)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_13)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_14)+
(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_15)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_16)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_17)+
(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_18)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_19)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_20)+
(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_21)+(NOKLTE_PS_LPQUL_MNC1_RAW.RSSI_PUSCH_LEVEL_22)),2))
-
decode(sum((NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_1)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_2)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_3)+
(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_4)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_5)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_6)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_7)
+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_8)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_9)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_10)+
(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_11)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_12)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_13)+
(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_14)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_15)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_16)+
(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_17)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_18)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_19)+
(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_20)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_21)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_22)),0,0,round(sum(-10*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_1)-9*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_2)-7*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_3)-
5*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_4)-3*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_5)-1*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_6)
+1*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_7)+3*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_8)+5*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_9)+
7*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_10)+9*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_11)+11*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_12)+
13*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_13)+15*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_14)+17*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_15)+
19*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_16)+21*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_17)+23*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_18)+
25*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_19)+27*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_20)+29*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_21)+
30*(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_22))/sum((NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_1)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_2)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_3)+
(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_4)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_5)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_6)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_7)
+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_8)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_9)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_10)+
(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_11)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_12)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_13)+
(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_14)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_15)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_16)+
(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_17)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_18)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_19)+
(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_20)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_21)+(NOKLTE_PS_LPQUL_MNC1_RAW.SINR_PUSCH_LEVEL_22)),2))
 from c_lte_lncel lncel,NOKLTE_PS_LPQUL_MNC1_RAW
where NOKLTE_PS_LPQUL_MNC1_RAW.LNCEL_ID(+) = lncel.obj_gid
   and NOKLTE_PS_LPQUL_MNC1_RAW.LNCEL_ID(+) = lncel.obj_gid
   and lncel.conf_id = 1
   and NOKLTE_PS_LPQUL_MNC1_RAW.PERIOD_START_TIME >=
       to_date(&start_datetime, 'yyyymmddhh24')
   and NOKLTE_PS_LPQUL_MNC1_RAW.PERIOD_START_TIME <
       to_date(&end_datetime, 'yyyymmddhh24')
group by To_Char(NOKLTE_PS_LPQUL_MNC1_RAW.PERIOD_START_TIME, 'yyyy-mm-dd') ,
 lncel.lncel_enb_id,
 lncel.lncel_lcr_id       
